//**************************************************************
//                    Activity #9
//                    Name: Sung Hoo Hong
//                    Data Structures Date: 02/06/23
// ***************************************************************
//      This program simply is a Color Guessing Game
//      First, the program will generate the random number and then
//      change the number into the color. Then, the program will get
//      the color guess from the user and compare it with the color
//      chosen by the computer. The program will do this process for
//      10 times. At the end of the program, it will print how many
//      the user got the color chosen by the computer correct.
// *****************************************************************

import java.util.Random;
import java.util.Scanner;

public class ESP
{
    public static void main(String[] args)
    {
        // Get the input from the user
        Scanner input = new Scanner(System.in);
        int correct = 0;

        // Do the 10 rounds of the color guessing game
        for (int i = 1; i <= 10; i++)
        {
            // Generate random number to choose the color
            Random number = new Random();
            int randomNumber = number.nextInt(5);
            String color = null;

            // Set the color with the respect to the random number generated by the computer
            if (randomNumber == 0)
            {
                color = "red";
            }
            else if (randomNumber == 1)
            {
                color = "green";
            }
            else if (randomNumber == 2)
            {
                color = "blue";
            }
            else if (randomNumber == 3)
            {
                color = "orange";
            }
            else if (randomNumber == 4)
            {
                color = "yellow";
            }

            System.out.println(i + ". " + "What color has the computer chosen?");
            String userChoice = input.nextLine();

            // Compare the user input with the computer choice
            if (userChoice.equals(color))
            {
                System.out.println(">The computer choose " + color);
                correct++;
            }
            else
            {
                System.out.println(">The computer choose " + color);
            }

        }

        // Print how many rounds the user won
        System.out.println("You got " + correct + " out of 10 correct");
    }
}